ex81.settings:
  type: config_object
  label: 'Form Example Settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    important_number:
      type: integer
      label: 'Some important number'
    important_text:
      type: string
      label: 'Some text'
ex81.settings_news:
  type: config_object
  label: 'News filter form'
  mapping:
    sorted:
      type: string
      label: 'Sorted'
# Schema for the configuration files of the Beetroot Example module.
ex81.text_cleanup.settings:
  type: config_object
  label: 'Beetroot Example settings'
  mapping:
    example:
      type: string
      label: 'Example'
ex81.switch_theme:
  type: config_object
  label: 'Switch color theme'
  mapping:
    theme:
      type: string
      label: 'Theme'

ex81.ex81.*:
  type: config_entity
  label: ex81
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    text:
      type: string
      label: Type
    type:
      type: string
      label: Text
    plugins:
      type: sequence
      label: 'plugins'
      sequence:
        type: string
        label: 'plugins'
