_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  context: 0
  context_ui: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  ex81: 0
  ex81_content: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flexslider: 0
  flexslider_fields: 0
  flexslider_views: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  jsonapi: 0
  link: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  permissions_by_term: 0
  rdf: 0
  rest: 0
  restui: 0
  search: 0
  serialization: 0
  shortcut: 0
  slick: 0
  slick_paragraphs: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  classy: 0
  bootstrap5: 0
  bootstrap: 0
  custom_theme: 0
profile: minimal
