# Schema for the configuration files of the custom_plugin module.
custom_plugin.settings:
  type: config_object
  label: 'custom_plugin settings'
  mapping:
    example:
      type: string
      label: 'Example'

custom_plugin.custom_plugin.*:
  type: config_entity
  label: Custom plugin
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    plugins:
      type: sequence
      label: 'Plugins'
      sequence:
        type: string
        label: Plugins
